site_name: My Docs
nav:
  - Home: index.md
  - developer guide:
    - introduction: ./developer-guide/introduction.md
    - middleware: ./developer-guide/middleware.md
    - sip messages: ./developer-guide/sip-messages.md
    - sip dialogs: ./developer-guide/sip-dialogs.md
    - sip proxy: ./developer-guide/sip-proxy.md
    - call detail records: ./developer-guide/call-detail-records.md
    - advanced topics: ./developer-guide/advanced-topics.md 
  - drachtio server: 
    - installing: ./drachtio-server/installing.md
    - running: ./drachtio-server/running.md
    - configuring: ./drachtio-server/configuring.md
    - messaging protocol: ./drachtio-server/messaging-protocol.md
  - release notes:
    - drachtio-srf: ./release-notes/drachtio-srf/release-notes.md
    - drachtio-server: ./release-notes/drachtio-server/release-notes.md
  - API: 
    - Srf: ./api/srf/srf.md
  